### ISSUE TITLE
'fioctl devices config' crashes when supplied no argument

### ISSUE THREAD

**Issue by MatthewCroughan** [foundriesio/fioctl#36]
for example, `fioctl devices config updates` produces this.

```
panic: runtime error: index out of range [0] with length 0goroutine 1 [running]:
github.com/foundriesio/fioctl/subcommands/devices.doConfigUpdates(0xc00016e780, 0xdc3848, 0x0, 0x0)
	/home/matthew/git/fioctl/subcommands/devices/config_updates.go:102 +0x11a3
github.com/spf13/cobra.(*Command).execute(0xc00016e780, 0xdc3848, 0x0, 0x0, 0xc00016e780, 0xdc3848)
	/home/matthew/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xd53ba0, 0x4454ca, 0xd5cfa0, 0xc000000180)
	/home/matthew/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/matthew/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/foundriesio/fioctl/cmd.Execute()
	/home/matthew/git/fioctl/cmd/root.go:37 +0x31
main.main()
	/home/matthew/git/fioctl/main.go:6 +0x20
```

There are probably other places that this happens or will happen in future and I'd be interested to try and make a test for it. I'll check other projects and see how they do it.

**Comment by doanac** [comment]
should be fixed in master now.
