### ISSUE TITLE
'fioctl devices config updates' crashes when given 0 arguments

### ISSUE THREAD

**Issue by MatthewCroughan** [foundriesio/fioctl#41]
Almost identical to https://github.com/foundriesio/fioctl/issues/36

If any command is given to `fioctl devices config updates` without an argument, it will crash like this:

```
matthew@thinkpad ~/git/bebop/containers (master) $ fioctl devices config updates --apps httpd
panic: runtime error: index out of range [0] with length 0goroutine 1 [running]:
github.com/foundriesio/fioctl/subcommands/devices.doConfigUpdates(0xc00016e780, 0xc00000f340, 0x0, 0x2)
	/home/matthew/git/fioctl/subcommands/devices/config_updates.go:102 +0x11a3
github.com/spf13/cobra.(*Command).execute(0xc00016e780, 0xc00000f300, 0x2, 0x2, 0xc00016e780, 0xc00000f300)
	/home/matthew/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xd53ba0, 0x4454ca, 0xd5cfa0, 0xc000000180)
	/home/matthew/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/matthew/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/foundriesio/fioctl/cmd.Execute()
	/home/matthew/git/fioctl/cmd/root.go:37 +0x31
main.main()
	/home/matthew/git/fioctl/main.go:6 +0x20
```

```
matthew@thinkpad ~/git/bebop/containers (master) $ fioctl devices config updates --compose-apps
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/foundriesio/fioctl/subcommands/devices.doConfigUpdates(0xc000198780, 0xc0001116c0, 0x0, 0x1)
	/home/matthew/git/fioctl/subcommands/devices/config_updates.go:102 +0x11a3
github.com/spf13/cobra.(*Command).execute(0xc000198780, 0xc0001116a0, 0x1, 0x1, 0xc000198780, 0xc0001116a0)
	/home/matthew/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xd53ba0, 0x4454ca, 0xd5cfa0, 0xc000000180)
	/home/matthew/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/matthew/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/foundriesio/fioctl/cmd.Execute()
	/home/matthew/git/fioctl/cmd/root.go:37 +0x31
main.main()
	/home/matthew/git/fioctl/main.go:6 +0x20
```

**Comment by doanac** [comment]
I don't think your fioctl is up-to-date. I'm running the master version of fioctl and don't see this:
~~~
$ fioctl devices config updates --compose-apps
Error: accepts 1 arg(s), received 0
Usage:
  fioctl devices config updates <device> [flags]

Flags:
      --apps string          comma,separate,list
      --compose-apps         Migrate device from docker-apps to compose-apps
      --compose-dir string   The directory to install compose apps in (default "/var/sota/compose")
      --dryrun               Only show what would be changed
  -h, --help                 help for updates
      --tags string          comma,separate,list

Global Flags:
  -c, --config string   config file (default is $HOME/.config/fioctl.yaml)
  -t, --token string    API token from https://app.foundries.io/settings/tokens/
  -v, --verbose         Print verbose logging

accepts 1 arg(s), received 0
~~~

**Comment by MatthewCroughan** [comment]
This is true, I was not testing master so assumed this was a separate bug.
